use_frameworks!

platform :ios, '12.0'
use_modular_headers!
target 'KitBase_Example' do
  pod 'KitBase', :path => '../'
  pod 'Alamofire', '5.2.1'
  target 'KitBase_Tests' do
    inherit! :search_paths

    
  end
end
